### ISSUE TITLE
Error Using SdrBirdrecMex

### ISSUE THREAD

**Issue by birdguy3227** [rlinus/SdrBirdrec#1]
Even after adding testSdrBirdrecBackend.m to the PATH, I still get the error message below when trying to start SDRBirdRec. I have NIMAX installed, but I don't need a DAQ card to test the radio, correct?

Error using SdrBirdrecMex
initRec: NIDAQmxSourceActivitiy: DAQmxCreateAIVoltageChan: Device identifier is invalid.
Device Specified: Dev1

Task Name: ADC task

Status Code: -200220

Error in SdrBirdrecBackend/initRec (line 144)
            SdrBirdrecMex('initRec', this.objectHandle, params);

Error in recorder (line 238)
    sdrBirdrecBackend.initRec(params);

Error in sdr_birdrec>startrec_btn_Callback (line 360)
    recorder(handles.sdr_device_btn.UserData.sdrBirdrecBackend, settings,gui_handles);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in sdr_birdrec (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)sdr_birdrec('startrec_btn_Callback',hObject,eventdata,guidata(hObject))
 
Error while evaluating UIControl Callback.

**Comment by rlinus** [comment]
you don't need to add testSdrBirdrecBackend.m to the path, it's just a script to test basic functionality like device loading. The error is because SdrBirdrec is trying to load the ni daq device "Dev1", which is probably not connected to your computer. you gotta set the DAQmx settings correctly (0 daqmx channels if you have no daqmx device connected).

best
Linus

**Comment by birdguy3227** [comment]
Ok, understood. I've changed the DAQmx settings in the GUI. However, the error message is still mostly the same. In response to the first message I tried changing the max frequency in the channel list to 350 MHz, but the same error results. 

The error message:

Error using SdrBirdrecMex
initRec: Invalid channel_bands parameter. At least one channel is out of bandwith.

Error in SdrBirdrecBackend/initRec (line 144)
SdrBirdrecMex('initRec', this.objectHandle, params);

Error in recorder (line 238)
    sdrBirdrecBackend.initRec(params);

Error in sdr_birdrec>startrec_btn_Callback (line 360)
    recorder(handles.sdr_device_btn.UserData.sdrBirdrecBackend, settings,gui_handles);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in sdr_birdrec (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)sdr_birdrec('startrec_btn_Callback',hObject,eventdata,guidata(hObject))
 
Error while evaluating UIControl Callback.

Best,
Amanuel

**Comment by rlinus** [comment]
You must set the channel_bands so that the the min. and max freq. are in the range sdr_center_frequency +- sdr_sample_rate/2

**Comment by birdguy3227** [comment]
I see the same error as above even when I type 298.8 and 301.2 for min and max freq., respectively, into the GUI (for sampling rate of 2.4MHz). Where exactly should I set the channel bands? I can see the param list in recorder.m:

 params.SDR_ChannelBands = settings.channel_list{:,3:4}*1e6

Do I edit this to the formula you mention?

**Comment by rlinus** [comment]
No, the formula just specifies the valid range. It must be **in** this range, so you must make the maximum slightly smaller. You can find help about valid ranges for parameters in the file SdrBirdrecBackend.m.

**Comment by birdguy3227** [comment]
Thanks for all the help, it started recording!
